
input_features = TotalFeatures';
numOfNeuronL1 = 8000;
autoencL1 = trainAutoencoder(input_features, numOfNeuronL1, ...
    'MaxEpochs', 20, ...
    'L2WeightRegularization', 0.002,...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.1, ...
    'ScaleData', false);

L1_features = encode(autoencL1, input_features);


numOfNeuronL4 = 1000;
autoencL2 = trainAutoencoder(L1_features, numOfNeuronL4, ...
    'MaxEpochs', 20, ...
    'L2WeightRegularization', 0.002,...
    'SparsityRegularization', 4, ...
    'SparsityProportion', 0.1, ...
    'ScaleData', false);

L4_features = encode(autoencL2, L1_features);

deep_auto_encoder = stack(autoencL1, autoencL2);

view(deep_auto_encoder)